project/config/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('cliente/', include('cliente.urls')),
    path('producto/', include('producto.urls')),
    ]

project/core/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

app_name= "core"
urlpatterns = [
    path("",views.inicio, name='inicio'), 
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(template_name="core/logout.html"), name="logout"),
    path("register/", views.register, name="register"), 
]

project/producto/urls.py
from django.urls import path
from . import views

app_name= "producto"

urlpatterns = [
    path("",views.inicio, name= 'inicio'), 
    path("productocategoria/create/", views.productocategoria_create, name="productocategoria_create"),
    path("productocategoria/list/", views.productocategoria_list, name="productocategoria_list"),
    path("productocategoria/detail/<int:pk>", views.productocategoria_detail, name="productocategoria_detail"),
    path("productocategoria/update/<int:pk>", views.productocategoria_update, name="productocategoria_update"),
     path("productocategoria/delete/<int:pk>", views.productocategoria_delete, name="productocategoria_delete"),
]

project/cliente/models.py
from django.db import models

# Create your models here.

class Pais(models.Model):

    nombre = models.CharField(max_length=50, verbose_name="país")

    def __str__(self):

        return self.nombre
    class Meta:
        verbose_name_plural= "países"

class Cliente(models.Model):

    nombre = models.CharField(max_length=50)

    apellido = models.CharField(max_length=50)

    nacimiento = models.DateField(null=True)

    pais_origen_id = models.ForeignKey(Pais, on_delete=models.SET_NULL, null=True, verbose_name="país de origen")

    def __str__(self):

        return f"{self.nombre} {self.apellido}"

project/core/models.py
from django.db import models

# Create your models here.

project/producto/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class ProductoCategoria (models.Model):
    '''Categoria de productos'''
    nombre = models.CharField(max_length=200, unique=True)
    descripcion = models.CharField(max_length=250, null=True, blank=True, verbose_name ='descripcion')

    def __str__(self) -> str:
        return self.nombre
    
    class Meta:
        verbose_name = "categoría de productos"
        verbose_name_plural = "categorías de productos"

class Producto(models.Model):
    categoria_id = models.ForeignKey(ProductoCategoria,null=True, on_delete=models.CASCADE)  
    nombre= models.CharField(max_length=100)      
    unidad_medida = models.CharField(max_length=100)
    cantidad = models.FloatField()
    precio =models.FloatField()
    descripcion = models.TextField(null=True, blank = True, verbose_name="descripcion")
    fecha_actualizacion =  models.DateField(
        null=True, blank=True,default=timezone,editable=False, verbose_name="fecha de actualizacion"
    )

    def __str__(self) -> str:
        return f"{self.nombre} ({self.unidad_medida}) ${self.precio:.2f}"

    class Meta: 
        verbose_name = "producto"
        verbose_name_plural= "productos"

project/core/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields= ["username", "password"]
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "password": forms.PasswordInput(attrs={"class": "form-control"}),
        }
        
class CustomUserCreationForm(UserCreationForm):
    class Meta: 
        model= User
        fields= ["username", "password1", "password2"]
        widgets= {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "password1": forms.PasswordInput(attrs={"class": "form-control"}),
            "password2": forms.PasswordInput(attrs={"class": "form-control"}),

        }

project/producto/forms.py
from django import forms
from . import models

#class ProductoCategoriaForm(forms.form):
 #   nombre= forms.CharField()
 #   descripcion= forms.CharField()


class ProductoCategoriaForm(forms.ModelForm):
    class Meta():
        model= models.ProductoCategoria
        fields="__all__"
        widgets= {
            "nombre":forms.TextInput(attrs={"class":"form-control"}),
            "descripcion": forms.TextInput(attrs={"class":"form-control"}),
        }

project/cliente/views.py
from django.shortcuts import render

# Create your views here.
from . import models
def inicio(request):
    consulta_de_clientes = models.Cliente.objects.all()
    context={"clientes": consulta_de_clientes}
    return render(request, "cliente/index.html", context)

project/config/views.py
from django.http import HttpResponse 
from django.template import Context , Template
from django.shortcuts import render




def probando_template(request):
    mi_html = open("./templates/template1.html") 
    mi_template = Template(mi_html.read()) 
    mi_html.close()
    mi_contexto = Context()
    mi_documento = mi_template.render(mi_contexto)
    return HttpResponse(mi_documento)

project/core/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.http import HttpResponse , HttpRequest
from django.shortcuts import render
from .forms import CustomAuthenticationForm, CustomUserCreationForm
from . import models

@login_required
def inicio(request):
    return render(request, "core/index.html")


class CustomLoginView(LoginView):
    authentication_form= CustomAuthenticationForm
    template_name= "core/login.html"


def register(request:HttpRequest):    
    if request.method =="POST":
        form=CustomAuthenticationForm(request.POST)
        if form.is_valid():
            username=form.cleaned_data["username"]
            form.save()
            return render(request, "core/index.html", {"mensaje":"Usuario creado"})
    else:
        form = CustomUserCreationForm()
    return render(request, "core/register.html",{"form":form})

project/producto/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.query import QuerySet
from django.shortcuts import render,  redirect
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy
from . import forms,models

from . import models
def inicio(request):

    return render(request, "producto/index.html")

def productocategoria_list(request):
    consulta = request.GET.get("consulta") 
    if consulta:
        print (consulta)
        query = models.ProductoCategoria.objects.filter(nombre__icontains=consulta)
    else:
        query = models.ProductoCategoria.objects.all()

    context = {"productos": query}
    return render(request, "producto/index.html")

def productocategoria_create(request):
    if request.method == "POST":
        form = forms.ProductoCategoriaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("producto:inicio")
    else:
        form = forms.ProductoCategoriaForm()
        return render(request, "producto/productocategoria_create.html",context={"form": form})

def productocategoria_detail(request,pk):
    query = models.ProductoCategoria.objets.get(id=pk)
    return render(request, "producto/productocategoria_detail.html", {"producto":query})

def productocategoria_update(request, pk):
    query= models.ProductoCategoria.objets.get(id=pk)
    if request.method == "POST":
        form = forms.ProductoCategoriaForm(request.POST, instance=query)
        if form.is_valid():
            form.save()
            return redirect("producto:productocategoria_list")
    else:
        form = forms.ProductoCategoriaForm(instance=query)
    return render(request, "producto/productocategoria_update.html",context={"form": form})

def productocategoria_delete(request, pk):
    query= models.ProductoCategoria.objets.get(id=pk)
    if request.method == "POST":
        query.delete()
        return redirect("producto:productocategoria_list")
    return render(request, "producto/productocategoria_delete.html",context={"producto": query})

project/cliente/templates/cliente/index.html
{% extends 'core/base.html' %}

{% block titulo %}
    Cliente
{% endblock titulo %}


{% block  contenido%}

    {% for cliente in clientes %}
        <h2>{{cliente.nombre}}</h2>
        <p>{{cliente.apellido}}</p>
        <p>{{cliente.nacimiento}}</p>
        <p>{{cliente.pais_origen_id}}</p>
    {% endfor %}
    
    

{% endblock contenido %}   

project/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>
            {% block title %}
                WUACO
            {% endblock title %}
        </title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'core/assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>

        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#!">Wuaco</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'core:inicio' %}">Inicio</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">Nosotros</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'cliente:inicio' %}">Clientes</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'producto:inicio' %}">Productos</a></li>
                        <li class="nav-item"><a class="nav-link text-bg-info ">{{ user.username }}</a></li>
                        <li class="nav-item ">
                            <form action="{% url 'core:logout' %}" method="post"></form>
                                {% csrf_token %}    
                                <button type = "submit" class="btn btn-dark">Logout</button>
                            </form> 
                        </li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'core:login' %}">Login</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'core:register' %}">Registrarse</a></li>
                        {% endif %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="{% url 'producto:inicio' %}" role="button" data-bs-toggle="dropdown" aria-expanded="false">Productos</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#!">All Products</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="#!">Popular Items</a></li>
                                <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                            </ul>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <button class="btn btn-outline-dark" type="submit">
                            <i class="bi-cart-fill me-1"></i>
                            Carrito
                            <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>
                        </button>
                    </form>
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Tu tienda digital</h1>
                    <p class="lead fw-normal text-white-50 mb-0">compra ahora</p>
                </div>
            </div>
        </header>
        <!-- Section-->
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">

                {% block titulo %}
                {% endblock titulo %}

                {% block contenido %}
                {% endblock contenido %}

           
        </section>
        <!-- Footer-->
        <footer class="py-2 bg-dark fixed-bottom ">
            <div class="container"><p class="m-0 text-center text-white">Wuaco &copy;</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'core/js/scripts.js' %}"></script>
    </body>
</html>

project/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block titulo %}
    WUACO
{% endblock titulo %}

{% block contenido %}
    {% if user.is_authenticated%}
        {{mensaje}}
        <p class = "fs-2">Bienvenido {{user.username}}</p>
    {% endif %}
<div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
    <div class="col mb-5">
        <div class="card h-100">
            <!-- Product image-->
            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
            <!-- Product details-->
            <div class="card-body p-4">
                <div class="text-center">
                    <!-- Product name-->
                    <h5 class="fw-bolder">Fancy Product</h5>
                    <!-- Product price-->
                    $40.00 - $80.00
                </div>
            </div>
            <!-- Product actions-->
            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">View options</a></div>
            </div>
        </div>
    </div>
    <div class="col mb-5">
        <div class="card h-100">
            <!-- Sale badge-->
            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
            <!-- Product image-->
            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
            <!-- Product details-->
            <div class="card-body p-4">
                <div class="text-center">
                    <!-- Product name-->
                    <h5 class="fw-bolder">Special Item</h5>
                    <!-- Product reviews-->
                    <div class="d-flex justify-content-center small text-warning mb-2">
                        <div class="bi-star-fill"></div>
                        <div class="bi-star-fill"></div>
                        <div class="bi-star-fill"></div>
                        <div class="bi-star-fill"></div>
                        <div class="bi-star-fill"></div>
                    </div>
                    <!-- Product price-->
                    <span class="text-muted text-decoration-line-through">$20.00</span>
                    $18.00
                </div>
            </div>
            <!-- Product actions-->
            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
            </div>
        </div>
    </div>
    <div class="col mb-5">
        <div class="card h-100">
            <!-- Sale badge-->
            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
            <!-- Product image-->
            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
            <!-- Product details-->
            <div class="card-body p-4">
                <div class="text-center">
                    <!-- Product name-->
                    <h5 class="fw-bolder">Sale Item</h5>
                    <!-- Product price-->
                    <span class="text-muted text-decoration-line-through">$50.00</span>
                    $25.00
                </div>
            </div>
            <!-- Product actions-->
            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
            </div>
        </div>
    </div>
    <div class="col mb-5">
        <div class="card h-100">
            <!-- Product image-->
            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
            <!-- Product details-->
            <div class="card-body p-4">
                <div class="text-center">
                    <!-- Product name-->
                    <h5 class="fw-bolder">Popular Item</h5>
                    <!-- Product reviews-->
                    <div class="d-flex justify-content-center small text-warning mb-2">
                        <div class="bi-star-fill"></div>
                        <div class="bi-star-fill"></div>
                        <div class="bi-star-fill"></div>
                        <div class="bi-star-fill"></div>
                        <div class="bi-star-fill"></div>
                    </div>
                    <!-- Product price-->
                    $40.00
                </div>
            </div>
            <!-- Product actions-->
            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
            </div>
        </div>
    </div>
    <div class="col mb-5">
        <div class="card h-100">
            <!-- Sale badge-->
            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
            <!-- Product image-->
            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
            <!-- Product details-->
            <div class="card-body p-4">
                <div class="text-center">
                    <!-- Product name-->
                    <h5 class="fw-bolder">Sale Item</h5>
                    <!-- Product price-->
                    <span class="text-muted text-decoration-line-through">$50.00</span>
                    $25.00
                </div>
            </div>
            <!-- Product actions-->
            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
            </div>
        </div>
    </div>
    <div class="col mb-5">
        <div class="card h-100">
            <!-- Product image-->
            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
            <!-- Product details-->
            <div class="card-body p-4">
                <div class="text-center">
                    <!-- Product name-->
                    <h5 class="fw-bolder">Fancy Product</h5>
                    <!-- Product price-->
                    $120.00 - $280.00
                </div>
            </div>
            <!-- Product actions-->
            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">View options</a></div>
            </div>
        </div>
    </div>
    <div class="col mb-5">
        <div class="card h-100">
            <!-- Sale badge-->
            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
            <!-- Product image-->
            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
            <!-- Product details-->
            <div class="card-body p-4">
                <div class="text-center">
                    <!-- Product name-->
                    <h5 class="fw-bolder">Special Item</h5>
                    <!-- Product reviews-->
                    <div class="d-flex justify-content-center small text-warning mb-2">
                        <div class="bi-star-fill"></div>
                        <div class="bi-star-fill"></div>
                        <div class="bi-star-fill"></div>
                        <div class="bi-star-fill"></div>
                        <div class="bi-star-fill"></div>
                    </div>
                    <!-- Product price-->
                    <span class="text-muted text-decoration-line-through">$20.00</span>
                    $18.00
                </div>
            </div>
            <!-- Product actions-->
            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
            </div>
        </div>
    </div>
    <div class="col mb-5">
        <div class="card h-100">
            <!-- Product image-->
            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
            <!-- Product details-->
            <div class="card-body p-4">
                <div class="text-center">
                    <!-- Product name-->
                    <h5 class="fw-bolder">Popular Item</h5>
                    <!-- Product reviews-->
                    <div class="d-flex justify-content-center small text-warning mb-2">
                        <div class="bi-star-fill"></div>
                        <div class="bi-star-fill"></div>
                        <div class="bi-star-fill"></div>
                        <div class="bi-star-fill"></div>
                        <div class="bi-star-fill"></div>
                    </div>
                    <!-- Product price-->
                    $40.00
                </div>
            </div>
            <!-- Product actions-->
            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
            </div>
        </div>
    </div>
</div>
{% endblock contenido %}

project/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block titulo %}
    Login
{% endblock titulo %}

{% block contenido %}
<div class="container">
    <h1 class="mt-4 ">Login</h1>
</div>

<form method="post">
    {%csrf_token%}
    {{form.as_p}}
    <input type="hidden" name="next" value="{%url'core:inicio'%}">
    <button type="submit" class="btn btn-primary">Inicio Sesion</button>
    <a href="{% url 'core:inicio' %}" class="btn btn-secondary ">Cancelar</a>
</form>
{%endblock contenido %}
    

project/core/templates/core/logout.html
{% extends 'core/base.html' %}
{% block titulo %}
    Logout
{% endblock titulo %}

{% block contenido %}
    <h1 class="display-4 ">Has cerrado sesion </h1>
{% endblock contenido %}
    

project/core/templates/core/register.html
{% extends 'core/base.html' %}

{% block titulo %}
    Registro
{% endblock titulo %}

{% block contenido %}
<div class="container">
    <h1 class="mt-4 ">Registro de usuario</h1>
</div>

<form method="post">
    {%csrf_token%}
    {{form.as_p}}
   
    <button type="submit" class="btn btn-success">Registar nuevo ususario</button>
    
</form>
{%endblock contenido %}
    

project/producto/templates/producto/index.html
> {% extends 'core/base.html' %}

{% block titulo %}
    App Productos
{% endblock titulo %}
{% block contenido %}
    <div class="fs-3 pb-5 ">
        <a href="{% url 'producto:productocategoria_create' %}">crear categorias de productos</a>
    </div>
    <div class="fs-3 pb-5 ">
        <a href="{% url 'producto:productocategoria_list' %}">Listar categorias de productos</a>
    </div>  
    <div class="fs-3 pb-5 ">
        <a href="{% url 'producto:inicio' %}">Volver a inicio</a>
    </div>  


    

{% endblock contenido %}   

project/producto/templates/producto/productocategoria_create.html
{% extends 'core/base.html' %}

{% block titulo %}
    Categoria de productos : Creacion
{% endblock titulo %}

{% block contenido %}
    <form action=""method="post">
        <p>nombre: <input type="text" name= "nombre"></p>
        <p>Descripcion: <input type = "text" name="descripcion"></p>
        <button type="submit">Guardar</button>
    </form>
{% endblock contenido %}

project/producto/templates/producto/productocategoria_delete.html
{% extends 'core/base.html' %}

{% block titulo %}

    Productos: Eliminar una  categoria de productos
    
{%endblock titulo  %}

{% block contenido %}
    <p class= "fs-5 fst-italic">¿Estas seguro que desea eliminar "{{producto.nombre}}"? </p>
    
  <form method= "post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger ">Confirmar</button>
  </form>
  <div class="fs-3 pb-4">
    <a href="{% url 'producto:inicio' %}">Volver al inicio de productos</a>
</div>   
{% endblock contenido %}

project/producto/templates/producto/productocategoria_detail.html
> {% extends 'core/base.html' %}
{% block titulo %}
    Productos : Detalle de una categoria de productos
{% endblock titulo %}
{% block contenido %}
    <ul>
        <li>Nombre : {{producto.nombre}}</li>
        <li>Descripcion:{{producto.descripcion}}</li>
    </ul>
    <div class="fs-3 pb-5 ">
        <a href="{% url 'producto:productocategoria_list' %}">Volver al inicio de productos</a>
    </div>  

{% endblock contenido %}   

project/producto/templates/producto/productocategoria_form.html
{% extends 'core/base.html' %}

{% block titulo %}

    {%if form.instance.pk%}
      Editar
    {% else %}
      Crear
    {%endif%}
    Categoria de Productos
{%endblock titulo  %}

{% block contenido %}
    
  <form method= "post">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <button type="submit">Guardar</button>
  </form>
  <div class="fs-3 pb-5 ">
    <a href="{% url 'producto:inicio' %}">Volver al inicio de productos</a>
</div>   
{% endblock contenido %}

project/producto/templates/producto/productocategoria_list.html
> {% extends 'core/base.html' %}
{% block titulo %}
    Productos : Lista de categoria de productos
{% endblock titulo %}
{% block contenido %}
    <div>class="py-lg-4">
        <form action="{% url 'producto:inicio' %}" method=get>
            <input type= "text" name="consulta" placeholder="Buscar..."> 
        </form> 
    </div>
    <ul>
    {% for producto  in productos %} 
    <li>{{producto}}
        <a href="{% url 'producto:productocategoria_detail'producto.id %}">Ver detalle</a>
        <a href="{% url 'producto:productocategoria_update'producto.id %}">Cambiar</a>
        <a href="{% url 'producto:productocategoria_delete'producto.id %}">Eliminar</a>

    </li>{% endfor %}
    </ul>
    <div class="fs-3 pb-5 ">
        <a href="{% url 'producto:inicio' %}">Volver al inicio de productos</a>
    </div>  

{% endblock contenido %}   

project/producto/templates/producto/productocategoria_update.html
{% extends 'core/base.html' %}

{% block titulo %}

    Productos: Cambiar una categoria de productos
{%endblock titulo  %}
{% block contenido %}
    
  <form method= "post">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <button type="submit">Guardar</button>
  </form>
  <div class="fs-3 pb-5 ">
    <a href="{% url 'producto:productocategoria_list' %}">Volver</a>
</div>   

{% endblock contenido %}

project/templates/notas.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>estas son mis notas</h1>
</body>
</html>

project/templates/template1.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Wuaco</title>
</head>
<body>
    <h1>CARTERAS</h1>
    <p>Cartera KarolG 😍</p>
    
</body>
</html>